#!/bin/dash

tmpbotPID=`pgrep node`

if pgrep node >/dev/null
then
	exit
else
	echo "Bot is down, restarting it."
	# !!!!! Change the next line to the path to your bot #
	node /path/to/bot.js >> /path/to/voidlog.txt &
fi

exit
