#!/bin/dash

# Edit line 13 with the path to your bot.js and where you'd like the bot to write the log to.
# If you want the log overwritten with every start, change ">>" to ">"

tmpbotPID=`pgrep node`

if pgrep node >/dev/null
then
	exit
else
	echo "Bot is down, restarting it."
	node /path/to/voidbot/bot.js >> /path/to/voidbot/logs/voidbot.log &
fi

exit
