#!/bin/dash

echo "
    ******************************
    *  Please enter an option... *
    *                            *
    *  1. Start Bot...           *
    *  2. Stop Bot...            *
    *  3. Restart Bot...         *
    *  4. Check log...           *
    *  5. Exit...                *
    *                            *
    ******************************\n"
botPID=`pgrep node`
echo "    Bot PID: " $botPID

read -p "    Option: " opt

case "$opt" in
	1)
		echo "    Starting bot..."
		node /path/to/bot.js >> /path/to/voidlog.txt &
		sleep 2s
		clear
		;;
	2)
		echo "    Stopping bot..."
		kill -9 $botPID
		sleep 1s
		clear
		;;
	3)
		echo "    Restarting bot..."
		kill -9 $botPID
		node /path/to/bot.js >> /path/to/voidlog.txt &
		sleep 2s
		echo "    Bot restarted."
		clear
		;;
	4)
		clear
		tail -n 10 /path/to/voidlog.txt
		sleep 0.4s
		;;
	5)
		echo "    Quitting this script..."
		sleep 1s
		clear
		exit
		;;
	*)
		clear
		echo "    Invalid option..."
		;;
esac

exec /usr/bin/voidconsole
